services:
  m365-monitor:
    image: ghcr.io/mischa323/ms365-app-secret-monitor:latest
    build: .
    ports:
      - "3000:3000"
    volumes:
      - m365_data:/data
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


volumes:
  m365_data:
